server:
  port: 8070

spring:
  cloud:
    stream:
      bindings:
        inboundTicketAlert:
          destination: ticketChangeTopic
          content-type: application/json
          group: supportGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

# eureka:
#   instance:
#     preferIpAddress: true
#   client:
#     registerWithEureka: true
#     fetchRegistry: true
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    edu.fiap.aula3: DEBUG
